### ISSUE TITLE
Right way to set the threads flag

### ISSUE THREAD

**Issue by kigero** [vegardit/haxe-concurrent#1]
I've incorporated this haxelib into a project that I'm working on which is currently targeting Java, and I was wondering how you were intending on the `threads `flag to be set: whether the haxelib has some magic that handles this on its own, or if I should be manually adding the `-D threads` argument in my build file (or using the `hx.concurrent.internal.Macros.addDefines()` macro). 

Basically, is the intention that I add the flag myself to builds that I know can handle threads, or is this something that should be handled by the haxelib - and if the latter, what's the right way to trigger this?  I'm setting it manually right now and it seems to be working well.

**Comment by sebthom** [comment]
The "magic" happens already here https://github.com/vegardit/haxe-concurrent/blob/master/extraParams.hxml
The macro is automatically executed when you reference the lib. See also http://nadako.github.io/HaxeManual/haxelib-extraParams.html

**Comment by kigero** [comment]
Figured it out I think - the package that gets installed via `haxelib install haxe-concurrent` doesn't have the extraParams.hxml file in it.

![image](https://user-images.githubusercontent.com/679688/45768507-194dee80-bc0b-11e8-810f-f4201878b03e.png)

If I add that file to the source directory parallel to the haxelib.json file, then threads is set and works as expected.  So may just be a packaging bug.

**Comment by sebthom** [comment]
Oh, I will have a look. Thanks!

**Comment by sebthom** [comment]
Fixed with new 2.0.0 release. Thanks for reporting!
