### ISSUE TITLE
Hashlink CG thread issue

### ISSUE THREAD

**Issue by rcstuber** [vegardit/haxe-concurrent#11]
When working with the `ThreadPool` on Hashlink the error below gets raised. This happens after the submitted tasks are executed.

``src/gc.c(232) : FATAL ERROR : Can't lock GC in unregistered thread``

OS: MacOS Catalina
Haxe version: 4.2.1+bf9ff69
Hashlink version: 1.12.0 (Github master)

Any ideas? Thanks in advance!

**Comment by sebthom** [comment]
Hmm I don't think I can help here. Seems to be an HashLink internal problem. You may have to open an issue in the [HashLink](https://github.com/HaxeFoundation/hashlink) repo with a small reproducer.

**Comment by rcstuber** [comment]
Thanks, will be checking there. Closing.
