### ISSUE TITLE
How to ensure event is fired only Once!

### ISSUE THREAD

**Issue by darmie** [vegardit/haxe-concurrent#13]
I am using the `hx.concurrent.event` package to implement a wrapper for an EventEmitter based on the Javascript EventEmitter API. 

This is my implementation 
```hx
class EventEmitter {
	final signals:Map<String, SyncEventDispatcher<haxe.Rest<Any>>>;
    final one_signals:Map<String, SyncEventDispatcher<haxe.Rest<Any>>>;
    final one_listeners:Map<String, Array<(...v:Any) -> Void>>;
    // static final executor:Executor = Executor.create(2);
	public function new() {
		signals = new Map();
        one_signals = new Map();
        one_listeners = new Map();
	}
    public function setMaxListeners(count:Int) {
		// maxListeners = count;
	}
	public function on(name:String, callback:(...v:Any) -> Void) {
		var asyncDispatcher = new SyncEventDispatcher<haxe.Rest<Any>>();
		if (signals.exists(name)) {
			signals.get(name).subscribe(callback);
		} else {
            asyncDispatcher.subscribe(callback);
			signals.set(name, asyncDispatcher);
		}
	}
	public function once(name:String, callback:(...v:Any) -> Void) {
		var asyncDispatcher = new SyncEventDispatcher<haxe.Rest<Any>>();
		asyncDispatcher.subscribe(callback);
		if (one_signals.exists(name)) {
            var s = one_signals.get(name);
			s.subscribe(callback);
		} else {
            asyncDispatcher.subscribe(callback);
			one_signals.set(name, asyncDispatcher);
		}
        if(one_listeners.exists(name)){
            var l = one_listeners.get(name);
            l.push(callback);
        } else {
            one_listeners.set(name, [callback]);
        }
	}
	public function emit(name:String, ...v:Any) {
		if (signals.exists(name)) {
			final signal = signals.get(name);
            signal.fire(...v);
		}
        if(one_signals.exists(name)){
            final one_signal = one_signals.get(name);
            var s = one_signal.fire(...v);
            s.onResult = (result:FutureResult<Int>)->{
                switch result {
                    case SUCCESS(result, time, future):{
                        one_signal.unsubscribe(one_listeners[name][result-1]);
                        one_signals.remove(name);
                    }
                    case FAILURE(ex, _): trace('Event could not be delivered because of: $ex');
                    case _:
                }
            };
        }
	}
}
```
when I use `eventEmitter.once` function, an older listener still fires in another call. How do I ensure that a listener can only be fired one?

**Comment by sebthom** [comment]
I am not familar with the EventEmitter API. Can you provide a minimal self-containing runnable test class?

**Comment by darmie** [comment]
Hi @sebthom this is a reproducible class, it works for small test

```hx
import buddy.Buddy;

using buddy.Should;
/**
	@author Damilare Akinlaja
**/
class Main implements Buddy<[TestEvent]> {}

class TestEvent extends buddy.BuddySuite {
	public function new() {
		describe("Event emitter test", {
			it("should emit only once", (done) -> {
				final eventEmitter = new EventEmitter();
				eventEmitter.once('start', (values) -> {
					final start = values[0];
					final end = values[1];
					start.should.be(1);
					end.should.be(100);
					done();
				});
				eventEmitter.emit('start', 1, 100);
				eventEmitter.emit('start', 2, 100);
			});
		});
	}
}
```

But when I use it on a more bigger project and send many events, there is an obvious delay before listeners are triggered. 

It fails entirely on C++ target with timeout errors `Timeout after 5000 ms` in a more complex project with many events.

**Comment by sebthom** [comment]
Hi, the test works fine for me in CPP. But it fails for javascript. The reason seems to be your usage of the rest operator.

Testing with Javascript I get this error:
```
Event emitter test
  should emit only once (FAILED)
    Expected 100, was null
```

I guess the reason is your usage of the rest operator with the `EventDispatcher#fire` method which only declares on argument.
In Javascript if you pass more arguments to a function than it declares, the remaining arguments are silently dropped by the JS runtime. Interestingly tho, it works on all targets except JavaScript, so maybe this is a bug in Haxe's JS transpiler in the context of generics, the haxe.Rest type and the rest operator.

**Comment by darmie** [comment]
@sebthom noted! I'll fix that for JavaScript. 

I still wonder why I get timeout errors in C++ in my [project](https://github.com/zenturi/Zenflo).

**Comment by sebthom** [comment]
Without having looked into your project. Maybe your are running into race conditions because of multi-threading. I don't think the way you are accessing the maps in the EventEmitter is thread-safe.

**Comment by darmie** [comment]
@sebthom any idea how I can solve this problem?

**Comment by sebthom** [comment]
> @sebthom any idea how I can solve this problem?

You could try to guard all calls to a map with a dedicated hx.concurrent.RLock instance.
