### ISSUE TITLE
haxe-concurrent doesn't work in android

### ISSUE THREAD

**Issue by acarioni** [vegardit/haxe-concurrent#14]
Hello,

I’ve just opened [this issue](https://github.com/HaxeFoundation/haxe/issues/10571) about haxe-concurent in Android. I don’t think the problem is due to a flaw in the library, but maybe you have some clues.

**Comment by sebthom** [comment]
Does it work if you use the old java instead of the jvm target?

**Comment by acarioni** [comment]
Yes, it works with the option --java.

**Comment by sebthom** [comment]
Ok, then it is for sure a bug in the new jvm target and we will have to wait for it being acknowledged by the Haxe core developers and directly fixed in Haxe.
