### ISSUE TITLE
Thread Pool Spin Lock

### ISSUE THREAD

**Issue by onehundredfeet** [vegardit/haxe-concurrent#25]
Hi,

I'm just curious why you've chosen to use a spin lock on the thread pool implementation (with a short sleep).  For games, a sleep of 0.001 seconds can be a very long time.

**Comment by sebthom** [comment]
Hi, at the time being it was the easiest way to implement it cross target and it is sufficient for our use case (we don't use it for games).

Pull requests to improve the library and in this case to reduce latency are more than welcome!

**Comment by sebthom** [comment]
I published v5.1.0 including your PR. Thanks!

**Comment by onehundredfeet** [comment]
I think the merge may have gotten confused.  There’s now a compile error on line 114.  _pollPeriod should be pollPeriod.

**Comment by sebthom** [comment]
Yeah, that was a mistake. I just released 5.1.1.
