### ISSUE TITLE
Specific code fails to port to HTML5, Flash

### ISSUE THREAD

**Issue by FlashBacks1998** [vegardit/haxe-concurrent#28]
Im trying to learn the haxe-concurrent with OpenFL and it looks like I got some porting issues. The following code is self explanatory, create a bunch of threads with random as a test. On completion the code outputs the two times so I can see if working with multithreading is even worth it with my upcoming projects.
https://github.com/FlashBacks1998/haxe-concurrent-test
```
package;

import hx.concurrent.atomic.AtomicInt;
import hx.concurrent.Future;
import openfl.Lib;
import hx.concurrent.collection.SynchronizedArray;
import openfl.display.Sprite;
import openfl.text.TextField;
import hx.concurrent.executor.Executor;

class Main extends Sprite
{
    var executor:Executor = Executor.create(16);
    var label:TextField;

    public function new()
    {
        super();

		executor.start();		
		trace(executor.state);

		var array = new SynchronizedArray<Float>();
		var done = new AtomicInt();
		var futures = [];

		var task = function ():Void {
			var start = Lib.getTimer();
			var rand = Math.random() * 10000;

            do {
                rand = Math.random() * 10000;
            } while (rand > 10);

			array.add(rand);
			var progress = (done.incrementAndGet()/10);

			trace("task", progress, Lib.getTimer() - start, rand);
		}

		var start = Lib.getTimer();
		trace("submitting...");
		for (i in 0...1000)
		{
			futures.push(executor.submit(task));
			trace(i);
		}

		trace("waiting...");
		var result = executor.submit(task);
		
		trace(result);

		do {
			trace(done.toString());
		} while (!result.isComplete());

		var endConcurrent = Lib.getTimer() - start;
		trace("haxe-concurrent done", endConcurrent);

		start = Lib.getTimer();
		for (i in 0...1000)
			task();

		var endNative = Lib.getTimer() - start;
		trace("native done", endNative);

        // Display times in a TextField
        label = new TextField();
        label.text = "haxe-concurrent: " + endConcurrent + " ms\nnative: " + endNative + " ms";
        label.y = 50; // Adjust the vertical position of the label
        addChild(label);

		trace(futures);
    }
}
```

Ports to Windows, Linux, Neko, and HL works as intended. However when porting to HTML5 none of the tasks submitted to the executor actually work. I konw this because the `done` value never increments. When porting to Flash (RUFFLE) I get this error message;
`2024-02-01T18:39:50.345837Z ERROR ruffle_core::display_object::movie_clip: Got "Error: Error #1520: Mutex cannot be initialized." when constructing AVM2 side of movie clip of type boot_0453`. When using the native Flash player (v32)

```
Error: Error #1502: A script has executed for longer than the default timeout period of 15 seconds.
	at Main()
	at DocumentClass()
	at ApplicationMain$/start()
	at MethodInfo-99()
	at lime.app::_Event_Void_Void/dispatch()
	at openfl.display::Preloader/display_onUnload()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at openfl.display::DefaultPreloader/onLoaded()
	at openfl.display::DefaultPreloader/this_onComplete()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at openfl.display::Preloader/start()
	at MethodInfo-98()
	at lime.app::_Event_Void_Void/dispatch()
	at lime.utils::Preloader/start()
	at lime.utils::Preloader/updateProgress()
	at lime.utils::Preloader/current_onEnter()
```

What is going on? Where is the code breaking?

**Comment by sebthom** [comment]
HTLM and Flash targets are single threaded. So your loop
```haxe
		do {
			trace(done.toString());
		} while (!result.isComplete());
```
blocks any potential async execution.

Depending on the target platform a different Executor implementation is selected:
https://github.com/vegardit/haxe-concurrent/blob/4556ec016e43bd2dae6162887de62b2ee2c3a8e7/src/hx/concurrent/executor/Executor.hx#L33-L39

For HTML/Flash it is the TimerExecutor which uses `haxe.Timer` to schedule async execution of code. As long as you have actively running any code the execution of any scheduled async tasks is prevented.

To get true parallelism on the web one would need to use webworkers, however this has other consequences as they cannot access shared state but run in isolated processes.

**Comment by FlashBacks1998** [comment]
Out of curiosity, how can i wait or tell if all of the submissions in the TimerExecutor or ThreadPoolExecutor is completed? How would i fix the do while loop to not block any async execution?

**Comment by sebthom** [comment]
You need to get all your code after `executor.submit(...)` out of the event loop to allow the browser/flash to do event processing.
This means you need to work with callbacks. Something like:
```haxe
  trace("waiting...");
  var resultFuture = executor.submit(task);
  result.onCompletion(result => {
    // your code...
  });
```

For HTML or Flash using the Executor will not improve performance as still only a single thread (the event loop) running on a single core is used. This is a target specific limitation. To do parallelism in Browser/HTML you could play around with webworkers but as I said this does not work with shared states and involves serialization/message passing.
