### ISSUE TITLE
Package naming issue.

### ISSUE THREAD

**Issue by SyedAsimAliSE** [vegardit/haxe-concurrent#6]
Hi,

there is a problem with package naming, 

In source code it is 
```haxe
package hx.concurrent;
import hx.concurrent.lock.RLock;
```

and in physical folder it is:
```haxe
src/hx/concurrent
```
because of this none of the IDE's are able to recognize classes. 

Intellij will add the imports but can't recognize the classes. [cpp]
Flash Develop can't read the lib. [OpenFl]

what i did to solve :

just moved the hx pacakge out of src folder at library path.
```haxe
hx/concurrent
```

now the Intellij is able to recognize everything but in Flash Develop i had to add
the lib to the Global Class paths. 

thanks.

**Comment by sebthom** [comment]
I am using FlashDevelop this is working fine for me.

The haxelib.json defines the `src` folder as classpath: https://github.com/vegardit/haxe-concurrent/blob/master/haxelib.json#L5

To me it looks like an config issue in the IDE you are using.

**Comment by SyedAsimAliSE** [comment]
yes you are right , i just restarted my system and the Flash Develop is also recognizing it :)
