### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by melMass** [vegardit/haxe-concurrent#8]
Hi,

I'm trying to use the `executor` but I can't find a way to **wait for execution to complete**, all the examples from the readme are not contained so I can't reproduce any.
Do you have a simple working example besides the test file?

Thanks

**Comment by sebthom** [comment]
Hey Mel, if you post a small example how you are trying to use the executor I can probably show you what to do.

**Comment by sebthom** [comment]
Please open again in case you still need help.
