### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by azupko** [vegardit/haxe-concurrent#9]
Python 3.7 has marked await and async as reserved words.  Threads.await (and latch) will no longer run on systems using that.  await needs to be renamed either for all platforms or just python to work properly.

Created a fork with "a" fix but might not be the best.
https://github.com/azupko/haxe-concurrent

**Comment by sebthom** [comment]
Reserved keywords in specific targets should not be relevant for method names in Haxe code.
This issue seems to be a problem with Haxe 3.4+Python3.7 and is not present in Haxe 4+Python3.7. Therefore I'd like to not change the library.
